# ============================================================
# ============================================================
def calculate_statistics(numbers):
    n = len(numbers)
    total = sum(numbers)
    mean = total / n
    variance = sum((x - mean) ** 2 for x in numbers) / n
    print(f"Variance: {variance}")
    return variance


# ============================================================
# ============================================================
# def find_max_profit(prices):
#     min_price = float('inf')
#     max_profit = 0
#     for price in prices:
#         if price < min_price:
#             min_price = price
#         profit = price - min_price
#         if profit > max_profit:
#             max_profit = profit
#     return max_profit


# # ============================================================
# # ============================================================
# class OrderProcessor:
#     def __init__(self):
#         self.tax_rate = 0.1
#         self.discount_rate = 0.05
    
#     def calculate_total(self, items):
#         subtotal = sum(item['price'] * item['quantity'] for item in items)
#         tax = subtotal * self.tax_rate
#         discount = subtotal * self.discount_rate
#         total = subtotal + tax - discount
#         print(f"Final total: {total}")
#         return total


# # ============================================================
# # ============================================================
# class ReportGenerator:
#     def __init__(self):
#         self.template = "Report: {title}\n{content}\nGenerated by: {author}"
#         self.default_author = "System"
    
#     def generate(self, title, sections):
#         validated_title = title.strip().upper()
#         content_parts = []
#         for i, section in enumerate(sections):
#             formatted = f"{i+1}. {section}"
#             content_parts.append(formatted)
#         content = "\n".join(content_parts)
#         report = self.template.format(
#             title=validated_title,
#             content=content,
#             author=self.default_author
#         )
#         return report


# # ============================================================
# # ============================================================
# class TextAnalyzer:
#     def __init__(self):
#         self.results = {}
    
#     def analyze(self, text):
#         words = text.split()
#         count = len(words)
#         score = 0
#         for word in words:
#             if len(word) > 5:
#                 score += 2
#             else:
#                 score += 1
#         self.results[text[:20]] = score
#         return score


# # ============================================================
# # ============================================================
# def complex_calculation(a, b, c):
#     x = a + b
#     y = b + c
#     z = a + c
#     result1 = x * y
#     result2 = y * z
#     final = result1 + result2 + x + y + z
#     print(f"Final: {final}")
#     return final


# # ============================================================
# # ============================================================
# class OuterClass:
#     class InnerProcessor:
#         def __init__(self):
#             self.multiplier = 10
        
#         def process(self, values):
#             prepared = [v * 2 for v in values]
#             total = sum(prepared)
#             adjusted = total * self.multiplier
#             result = adjusted / len(prepared) if prepared else 0
#             return result
        